# Nazwa strony
title: Moja Strona

# Opis strony
description: To jest opis mojej strony.

# Ustawienia adresu URL (opcjonalne)
url: "https://czaroun.github.io"

# Ustawienia języka
lang: pl

# Konfiguracja głównej strony
home: coordinators_form_pl.html
